server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      default-filters:
        - Authentication
      routes:
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai-service/**
          filters:
            - RewritePath=/ai-service/(?<path>.*), /$\{path}

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}
            
        - id: user-service
          uri: lb://user-service
          predicates:  
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<path>.*), /$\{path}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - RewritePath=/review-service/(?<path>.*), /$\{path}

        - id: promotion-service
          uri: lb://promotion-service
          predicates:
            - Path=/promotion-service/**
          filters:
            - RewritePath=/promotion-service/(?<path>.*), /$\{path}

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - RewritePath=/inventory-service/(?<path>.*), /$\{path}

        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping-service/**
          filters:
            - RewritePath=/shipping-service/(?<path>.*), /$\{path}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service/(?<path>.*), /$\{path}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - http://localhost:3000
              - http://127.0.0.1:3000
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      revocation:
        fail-open: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
